version: 3
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - localhost
  localhost:
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    restart: always
