name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Sentry Deploys
          uses: tctree333/SciOlyID-Actions/sentry@master
          with:
            sentry auth: ${{ secrets.SENTRY_TOKEN }}
            sentry org: "sciolyid"
            sentry project 1: rfts-bot

        - name: Update Redis
          uses: tctree333/SciOlyID-Actions/update-redis@master
          with:
            dokku app name: rfts
            dokku host: ${{ secrets.DOKKU_HOST }}
            ssh private key: ${{ secrets.PRIVATE_KEY }}

            heroku email: ${{ secrets.HEROKU_EMAIL }}
            heroku token: ${{ secrets.HEROKU_TOKEN }}
            heroku app name: rfts

        - name: Deploy to Dokku
          uses: tctree333/SciOlyID-Actions/deploy-dokku@master
          with:
            dokku app name: rfts
            dokku host: ${{ secrets.DOKKU_HOST }}
            ssh private key: ${{ secrets.PRIVATE_KEY }}
